function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID6326\" class=\"headerLeftMenuInActive\"><a id=\"aID6326\" href=\"#\" OnMouseOver=\"link('_dir','macros0',this)\" class=\"leftMenuLinkHeadInActive\">macros</a></div>\n");
document.write("<div class=\"paragraphLeftMenu\">Macros</div>\n");
document.write("<div id=\"divID634\" class=\"leftMenuInActive\"><a id=\"aID634\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_BeginEventHandler1724412837',this)\" class=\"leftMenuLinkInActive\">COFFEE_BeginEventHandler</a></div>\n");
document.write("<div id=\"divID657\" class=\"leftMenuInActive\"><a id=\"aID657\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_BeginStateMachineStates3079579345',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_BeginStateMachineStates');\" onmouseout=\"return nd();\">COFFEE_BeginStateMachineS.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID663\" class=\"leftMenuInActive\"><a id=\"aID663\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_BeginStateMachineStateTransitions3079579345',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_BeginStateMachineStateTransitions');\" onmouseout=\"return nd();\">COFFEE_BeginStateMachineS.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID654\" class=\"leftMenuInActive\"><a id=\"aID654\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_BeginStateMachineTriggers3079579345',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_BeginStateMachineTriggers');\" onmouseout=\"return nd();\">COFFEE_BeginStateMachineT.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID646\" class=\"leftMenuInActive\"><a id=\"aID646\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_CreateModuleSingleton1807119661',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_CreateModuleSingleton');\" onmouseout=\"return nd();\">COFFEE_CreateModuleSingle.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID632\" class=\"leftMenuInActive\"><a id=\"aID632\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareAncestorEventHandler2364258463',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareAncestorEventHandler');\" onmouseout=\"return nd();\">COFFEE_DeclareAncestorEve.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID651\" class=\"leftMenuInActive\"><a id=\"aID651\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareEmptyStateTransition2287511142',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareEmptyStateTransition');\" onmouseout=\"return nd();\">COFFEE_DeclareEmptyStateT.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID631\" class=\"leftMenuInActive\"><a id=\"aID631\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareEventHandler2364258463',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareEventHandler');\" onmouseout=\"return nd();\">COFFEE_DeclareEventHandle.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID638\" class=\"leftMenuInActive\"><a id=\"aID638\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareExternEventHandler2461040540',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareExternEventHandler');\" onmouseout=\"return nd();\">COFFEE_DeclareExternEvent.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID644\" class=\"leftMenuInActive\"><a id=\"aID644\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareModuleSingleton1962421854',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareModuleSingleton');\" onmouseout=\"return nd();\">COFFEE_DeclareModuleSingl.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID649\" class=\"leftMenuInActive\"><a id=\"aID649\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareState3246468959',this)\" class=\"leftMenuLinkInActive\">COFFEE_DeclareState</a></div>\n");
document.write("<div id=\"divID648\" class=\"leftMenuInActive\"><a id=\"aID648\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareStateMachine3974048109',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareStateMachine');\" onmouseout=\"return nd();\">COFFEE_DeclareStateMachin.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID650\" class=\"leftMenuInActive\"><a id=\"aID650\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DeclareStateTransition2287511142',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DeclareStateTransition');\" onmouseout=\"return nd();\">COFFEE_DeclareStateTransi.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID647\" class=\"leftMenuInActive\"><a id=\"aID647\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_DestroyModuleSingleton1807119661',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_DestroyModuleSingleton');\" onmouseout=\"return nd();\">COFFEE_DestroyModuleSingl.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID637\" class=\"leftMenuInActive\"><a id=\"aID637\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_EndEventHandler2005388747',this)\" class=\"leftMenuLinkInActive\">COFFEE_EndEventHandler</a></div>\n");
document.write("<div id=\"divID659\" class=\"leftMenuInActive\"><a id=\"aID659\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_EndStateMachineStates1525466455',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_EndStateMachineStates');\" onmouseout=\"return nd();\">COFFEE_EndStateMachineSta.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID666\" class=\"leftMenuInActive\"><a id=\"aID666\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_EndStateMachineStateTransitions1525466455',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_EndStateMachineStateTransitions');\" onmouseout=\"return nd();\">COFFEE_EndStateMachineSta.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID656\" class=\"leftMenuInActive\"><a id=\"aID656\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_EndStateMachineTriggers1525466455',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_EndStateMachineTriggers');\" onmouseout=\"return nd();\">COFFEE_EndStateMachineTri.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID645\" class=\"leftMenuInActive\"><a id=\"aID645\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_ImplementModuleSingleton1962421854',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_ImplementModuleSingleton');\" onmouseout=\"return nd();\">COFFEE_ImplementModuleSin.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID652\" class=\"leftMenuInActive\"><a id=\"aID652\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_InitializeStateMachine2516855866',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_InitializeStateMachine');\" onmouseout=\"return nd();\">COFFEE_InitializeStateMac.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID660\" class=\"leftMenuInActive\"><a id=\"aID660\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnEnterState3246468959',this)\" class=\"leftMenuLinkInActive\">COFFEE_OnEnterState</a></div>\n");
document.write("<div id=\"divID667\" class=\"leftMenuInActive\"><a id=\"aID667\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnEnterStateTransition2287511142',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_OnEnterStateTransition');\" onmouseout=\"return nd();\">COFFEE_OnEnterStateTransi.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID661\" class=\"leftMenuInActive\"><a id=\"aID661\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnLeaveState3246468959',this)\" class=\"leftMenuLinkInActive\">COFFEE_OnLeaveState</a></div>\n");
document.write("<div id=\"divID668\" class=\"leftMenuInActive\"><a id=\"aID668\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnLeaveStateTransition2287511142',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_OnLeaveStateTransition');\" onmouseout=\"return nd();\">COFFEE_OnLeaveStateTransi.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID662\" class=\"leftMenuInActive\"><a id=\"aID662\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnUpdateState3246468959',this)\" class=\"leftMenuLinkInActive\">COFFEE_OnUpdateState</a></div>\n");
document.write("<div id=\"divID669\" class=\"leftMenuInActive\"><a id=\"aID669\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_OnUpdateStateTransition2287511142',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_OnUpdateStateTransition');\" onmouseout=\"return nd();\">COFFEE_OnUpdateStateTrans.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID642\" class=\"leftMenuInActive\"><a id=\"aID642\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterChildModule4142014580',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterChildModule');\" onmouseout=\"return nd();\">COFFEE_RegisterChildModul.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID643\" class=\"leftMenuInActive\"><a id=\"aID643\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterChildModuleInstance4045972450',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterChildModuleInstance');\" onmouseout=\"return nd();\">COFFEE_RegisterChildModul.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID665\" class=\"leftMenuInActive\"><a id=\"aID665\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterEmptyStateTransition1695946875',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterEmptyStateTransition');\" onmouseout=\"return nd();\">COFFEE_RegisterEmptyState.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID635\" class=\"leftMenuInActive\"><a id=\"aID635\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterEventHandler3835482080',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterEventHandler');\" onmouseout=\"return nd();\">COFFEE_RegisterEventHandl.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID639\" class=\"leftMenuInActive\"><a id=\"aID639\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterExternEventHandler2049930717',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterExternEventHandler');\" onmouseout=\"return nd();\">COFFEE_RegisterExternEven.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID641\" class=\"leftMenuInActive\"><a id=\"aID641\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterModule4142014580',this)\" class=\"leftMenuLinkInActive\">COFFEE_RegisterModule</a></div>\n");
document.write("<div id=\"divID658\" class=\"leftMenuInActive\"><a id=\"aID658\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterState3974002829',this)\" class=\"leftMenuLinkInActive\">COFFEE_RegisterState</a></div>\n");
document.write("<div id=\"divID664\" class=\"leftMenuInActive\"><a id=\"aID664\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterStateTransition1695946875',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterStateTransition');\" onmouseout=\"return nd();\">COFFEE_RegisterStateTrans.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID655\" class=\"leftMenuInActive\"><a id=\"aID655\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterStateTrigger3223924110',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterStateTrigger');\" onmouseout=\"return nd();\">COFFEE_RegisterStateTrigg.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID636\" class=\"leftMenuInActive\"><a id=\"aID636\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_RegisterTargetEventHandler2043639390',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_RegisterTargetEventHandler');\" onmouseout=\"return nd();\">COFFEE_RegisterTargetEven.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID629\" class=\"leftMenuInActive\"><a id=\"aID629\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_SendEvent2476867226',this)\" class=\"leftMenuLinkInActive\">COFFEE_SendEvent</a></div>\n");
document.write("<div id=\"divID630\" class=\"leftMenuInActive\"><a id=\"aID630\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_SendEventParams3511213114',this)\" class=\"leftMenuLinkInActive\">COFFEE_SendEventParams</a></div>\n");
document.write("<div id=\"divID640\" class=\"leftMenuInActive\"><a id=\"aID640\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_UnregisterExternEventHandler4293133161',this)\" class=\"leftMenuLinkInActive\" onmouseover=\"overLibLeftMenu();return overlib('COFFEE_UnregisterExternEventHandler');\" onmouseout=\"return nd();\">COFFEE_UnregisterExternEv.<img src=\"../../../../../../common/menunametolong.gif\"border=0></a></div>\n");
document.write("<div id=\"divID653\" class=\"leftMenuInActive\"><a id=\"aID653\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_UpdateStateMachine3974048109',this)\" class=\"leftMenuLinkInActive\">COFFEE_UpdateStateMachine</a></div>\n");
document.write("<div class=\"paragraphLeftMenu\">Defines</div>\n");
document.write("<div id=\"divID633\" class=\"leftMenuInActive\"><a id=\"aID633\" href=\"#\" OnMouseOver=\"link('_member','COFFEE_Event549438587',this)\" class=\"leftMenuLinkInActive\">COFFEE_Event</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
